# Classification Case Study
## Building models 

### Import libraries 

In [1]:
# Importing required packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style='white')

## Load data from final csv

In [2]:
train = pd.read_csv("final_train.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          564 non-null    object 
 1   Married         564 non-null    object 
 2   Dependents      564 non-null    int64  
 3   Education       564 non-null    object 
 4   SelfEmployed    564 non-null    object 
 5   LoanAmountTerm  564 non-null    float64
 6   CreditHistory   564 non-null    float64
 7   PropertyArea    564 non-null    object 
 8   LoanStatus      564 non-null    object 
 9   LoanAmountLog   564 non-null    float64
 10  IncomeLog       564 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 48.6+ KB


In [4]:
X = train.drop(columns=['LoanStatus'])
y = train.LoanStatus

In [5]:
X.shape

(564, 10)

In [6]:
X = pd.get_dummies(X)  # One Hot Encoding 

In [7]:
X.shape

(564, 16)

In [8]:
X.columns

Index(['Dependents', 'LoanAmountTerm', 'CreditHistory', 'LoanAmountLog',
       'IncomeLog', 'Gender_Female', 'Gender_Male', 'Married_No',
       'Married_Yes', 'Education_Graduate', 'Education_Not Graduate',
       'SelfEmployed_No', 'SelfEmployed_Yes', 'PropertyArea_Rural',
       'PropertyArea_Semiurban', 'PropertyArea_Urban'],
      dtype='object')

In [9]:
X.sample(5)

Dependents  LoanAmountTerm  CreditHistory  LoanAmountLog  IncomeLog  \
322           0           360.0            1.0       5.429346   9.114160   
476           0           360.0            1.0       4.553877   8.131531   
181           0           360.0            1.0       5.231109   9.399555   
39            0           360.0            1.0       4.897840   8.744647   
422           2           360.0            1.0       4.912655   8.378850   

     Gender_Female  Gender_Male  Married_No  Married_Yes  Education_Graduate  \
322              0            1           0            1                   1   
476              1            0           1            0                   0   
181              0            1           1            0                   1   
39               0            1           0            1                   1   
422              0            1           1            0                   1   

     Education_Not Graduate  SelfEmployed_No  SelfEmployed_Yes  \
322                       0                1                 0   
476                       1                1                 0   
181                       0                1                 0   
39                        0                1                 0   
422                       0                1                 0   

     PropertyArea_Rural  PropertyArea_Semiurban  PropertyArea_Urban  
322                   0                       1                   0  
476                   1                       0                   0  
181                   1                       0                   0  
39                    0                       1                   0  
422                   1                       0                   0

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Dependents              564 non-null    int64  
 1   LoanAmountTerm          564 non-null    float64
 2   CreditHistory           564 non-null    float64
 3   LoanAmountLog           564 non-null    float64
 4   IncomeLog               564 non-null    float64
 5   Gender_Female           564 non-null    uint8  
 6   Gender_Male             564 non-null    uint8  
 7   Married_No              564 non-null    uint8  
 8   Married_Yes             564 non-null    uint8  
 9   Education_Graduate      564 non-null    uint8  
 10  Education_Not Graduate  564 non-null    uint8  
 11  SelfEmployed_No         564 non-null    uint8  
 12  SelfEmployed_Yes        564 non-null    uint8  
 13  PropertyArea_Rural      564 non-null    uint8  
 14  PropertyArea_Semiurban  564 non-null    ui

### Split data into train and test data 

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [13]:
def print_scores(y_true, y_pred):
    cm = confusion_matrix(y_true,y_pred)
    tn = cm[0,0]
    tp = cm[1,1]
    fp = cm[0,1]
    fn = cm[1,0]
    print(f"Overall Accuracy             : {(tp + tn) / (tp + fp + tn + fn):.2f}")
    print(f"Positive Precision           : {tp / (tp + fp):.2f}")
    print(f"Negative Precision           : {tn / (tn + fn):.2f}")
    print(f"Recall or TPR or Sensitivity : {tp / (tp + fn):.2f}")
    print(f"Specificity or TNR           : {tn / (tn + fp):.2f}")      

## Logistic Regression

In [14]:
# Importing packages logistic regression and evaluation 
from sklearn.linear_model import LogisticRegression

In [15]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)

StandardScaler()

In [16]:
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [17]:
# logistic regression   
model = LogisticRegression()
model.fit(X_train_scaled,y_train)

LogisticRegression()

In [18]:
# Check model's performance with train data 
model.score(X_train_scaled,y_train)

0.8248337028824834

In [19]:
y_pred = model.predict(X_test_scaled)

In [20]:
accuracy_score(y_test,y_pred)

0.7787610619469026

In [21]:
confusion_matrix(y_test,y_pred)

array([[13, 22],
       [ 3, 75]], dtype=int64)

In [22]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.78
Positive Precision           : 0.77
Negative Precision           : 0.81
Recall or TPR or Sensitivity : 0.96
Specificity or TNR           : 0.37


### Display classification report

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           N       0.81      0.37      0.51        35
           Y       0.77      0.96      0.86        78

    accuracy                           0.78       113
   macro avg       0.79      0.67      0.68       113
weighted avg       0.79      0.78      0.75       113



In [24]:
(13 + 75) / (13 + 22 + 3 + 75)

0.7787610619469026

In [25]:
y_pred_prob = model.predict_proba(X_test_scaled)

In [26]:
model.coef_

array([[ 0.12504115, -0.06339225,  1.52887566, -0.07144193,  0.01978037,
        -0.04273509,  0.04273509, -0.08791328,  0.08791328,  0.04988399,
        -0.04988399, -0.01659069,  0.01659069, -0.14173176,  0.21747696,
        -0.08953919]])

In [27]:
y_pred_prob[:5], y_pred[:5]

(array([[0.24778533, 0.75221467],
        [0.10699829, 0.89300171],
        [0.12604105, 0.87395895],
        [0.12853865, 0.87146135],
        [0.23119301, 0.76880699]]),
 array(['Y', 'Y', 'Y', 'Y', 'Y'], dtype=object))

## Decision Tree

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
model = DecisionTreeClassifier(max_depth=5)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [48]:
model.score(X_train,y_train)

0.8558758314855875

In [49]:
y_pred = model.predict(X_test)

In [46]:
accuracy_score(y_test,y_pred)

0.6814159292035398

In [50]:
confusion_matrix(y_test,y_pred)

array([[15, 20],
       [ 5, 73]], dtype=int64)

In [51]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.78
Positive Precision           : 0.78
Negative Precision           : 0.75
Recall or TPR or Sensitivity : 0.94
Specificity or TNR           : 0.43


In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           N       0.75      0.43      0.55        35
           Y       0.78      0.94      0.85        78

    accuracy                           0.78       113
   macro avg       0.77      0.68      0.70       113
weighted avg       0.77      0.78      0.76       113



### Decision Tree Created by Classifier

In [37]:
# Print tree generated by DecisionTreeClassifier
from sklearn.tree import export_text
tree_rules = export_text(model, feature_names=list(X_train))
print(tree_rules)

|--- CreditHistory <= 0.50
|   |--- LoanAmountLog <= 6.30
|   |   |--- LoanAmountLog <= 4.86
|   |   |   |--- class: N
|   |   |--- LoanAmountLog >  4.86
|   |   |   |--- LoanAmountLog <= 4.88
|   |   |   |   |--- class: Y
|   |   |   |--- LoanAmountLog >  4.88
|   |   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |   |--- class: N
|   |   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |   |--- class: N
|   |--- LoanAmountLog >  6.30
|   |   |--- class: Y
|--- CreditHistory >  0.50
|   |--- IncomeLog <= 9.90
|   |   |--- IncomeLog <= 7.78
|   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |--- LoanAmountLog <= 4.01
|   |   |   |   |   |--- class: N
|   |   |   |   |--- LoanAmountLog >  4.01
|   |   |   |   |   |--- class: N
|   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |--- class: Y
|   |   |--- IncomeLog >  7.78
|   |   |   |--- LoanAmountTerm <= 48.00
|   |   |   |   |--- class: N
|   |   |   |--- LoanAmountTerm >  48.00
|   |

## KNN 

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [63]:
y_pred = model.predict(X_test_scaled)

In [64]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.75
Positive Precision           : 0.76
Negative Precision           : 0.71
Recall or TPR or Sensitivity : 0.94
Specificity or TNR           : 0.34


## Naive Bayes 

In [65]:
from sklearn.naive_bayes import GaussianNB

In [66]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [67]:
model.score(X_train,y_train)

0.8181818181818182

In [68]:
y_pred = model.predict(X_test)

In [69]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.79
Positive Precision           : 0.79
Negative Precision           : 0.79
Recall or TPR or Sensitivity : 0.95
Specificity or TNR           : 0.43


## Support Vector Machines

In [70]:
from sklearn.svm import SVC

In [73]:
model = SVC()
model.fit(X_train_scaled,y_train)

SVC()

In [74]:
model.score(X_train_scaled,y_train)

0.8337028824833703

In [75]:
y_pred = model.predict(X_test_scaled)

In [76]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.78
Positive Precision           : 0.77
Negative Precision           : 0.81
Recall or TPR or Sensitivity : 0.96
Specificity or TNR           : 0.37
